version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_HOST: '%'
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    #      MONGO_INITDB_DATABASE: init
    volumes:
      - ./db_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro
  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo_ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpassword
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpassword@mongo:27017/
